const actions = {
  SET_STATE_ALL: 'all/SET_STATE',
  SET_STATE_CLEAR: 'all/SET_STATE_CLEAR',
  SET_STATE: 'circles/SET_STATE',
  LOAD_CURRENT_CIRCLES: 'circles/LOAD_CURRENT_CIRCLES',
  SET_PRIMARY_CIRCLE: 'circles/SET_PRIMARY_CIRCLE',
  CREATE_CONVERSATION: 'circles/CREATE_CONVERSATION',
  GET_CONVERSATION_LINK: 'circles/GET_CONVERSATION_LINK',
  CREATE_CIRCLE: 'circles/CREATE_CIRCLE',
  DELETE_CIRCLE: 'circles/DELETE_CIRCLE',
  UPLOAD_KEY: 'circles/UPLOAD_KEY',
  DELETE_KEY: 'circles/DELETE_KEY',
  REQUEST_VOUCH: 'circles/REQUEST_VOUCH',
  CHECK_FOR_VOUCH: 'circles/CHECK_FOR_VOUCH',
  VOUCH: 'circles/VOUCH',
  REQUEST_ACCESS: 'circles/REQUEST_ACCESS',
  GRANT_ACCESS: 'circles/GRANT_ACCESS',
}

export default actions
